name: auth0/jwks-rsa-java/build-and-test

on:
  pull_request:
  merge_group:
  push:
    branches: ["master", "main"]

jobs:
  rl-scanner:
    uses: ./.github/workflows/rl-secure.yml
    with:
      java-version: 8
      artifact-name: 'jwks-rsa-${{ steps.get_version.outputs.version }}.jar"'
    secrets:
      RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
      RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
      SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
      PRODSEC_TOOLS_USER: ${{ secrets.PRODSEC_TOOLS_USER }}
      PRODSEC_TOOLS_TOKEN: ${{ secrets.PRODSEC_TOOLS_TOKEN }}
      PRODSEC_TOOLS_ARN: ${{ secrets.PRODSEC_TOOLS_ARN }}

  gradle:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - uses: gradle/gradle-build-action@a4cf152f482c7ca97ef56ead29bf08bcd953284c
        with:
          arguments: assemble apiDiff check jacocoTestReport --continue --console=plain
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        with:
          flags: unittests
      - uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: lib/build/reports
