name: auth0/jwks-rsa-java/build-and-test

on:
  pull_request:
  merge_group:
  push:
    branches: ["master", "main"]

jobs:
  gradle:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 8

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1

      - name: Test and Assemble and ApiDiff with Gradle
        run: ./gradlew assemble apiDiff check jacocoTestReport --continue --console=plain

      - uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
        with:
          flags: unittests
      - uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: lib/build/reports
